-- Pregunta 1
A = EMPLEATS(NUM_EMPL=2)
B = A*DEPARTAMENTS
C = B*PROJECTES
R = C[NOM_DPT,NOM_PROJ]

-- Pregunta 2
A = EMPLEATS(SOU>200000)
B = A*DEPARTAMENTS
C = B(CIUTAT_DPT = 'MADRID')
R = C[NUM_DPT,NOM_DPT]

-- Pregunta 3
A = EMPLEATS(CIUTAT_EMPL != 'MADRID')
B = A*DEPARTAMENTS
C = EMPLEATS*DEPARTAMENTS
D = B[NUM_DPT,NOM_DPT]
E = C[NUM_DPT,NOM_DPT]
R = E-D

-- Pregunta 4
A = EMPLEATS [NUM_DPT, CIUTAT_EMPL]
B = EMPLEATS [NUM_DPT, CIUTAT_EMPL]
C = B{NUM_DPT -> NUM_DPT2, CIUTAT_EMPL -> CIUTAT_EMPL2}
D = A[NUM_DPT = NUM_DPT2, CIUTAT_EMPL != CIUTAT_EMPL2]C
E = D[NUM_DPT]
F = E*DEPARTAMENTS
R = F[NUM_DPT, NOM_DPT]