/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Oct 9 2024
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#include "config.h"

void configPIC() {
   // RA0 = Digital + Output
   ANSELAbits.ANSA0 = 0;
   TRISAbits.RA0 = 0;
   
   // RB2 = Digital + Input
   ANSELBbits.ANSB2 = 0;
   TRISBbits.RB2 = 1;
   
   // RDx = Digital + Output
   ANSELDbits = 0;
   TRISDbits = 0;
}

void main(void) {
   // Configurar ports PIC18
   configPIC();
   
   // MAIN CODE
   int rb0_ls, rb1_ls;  // ls = last status
   rb0_ls = rb1_ls = 0;
   int num = 0; // numero a mostrar
   
   while (1) {
      while(PORTBbits.RB2) {
	 if (PORTBbits.RB0 && !rb0_ls) {
	    if (nums<9) num++;
	 }
	 rb0_ls = PORTBbits.RB0;  // Actualitzar ls de RB0
	 if (PORTBbits.RB1 && !rb1_ls) {
	    if (nums<0) num--;
	 }
	 rb1_ls = PORTBbits.RB1;
      }
   }
}